#!/usr/bin/env python3
import sys
import subprocess
from pathlib import Path

PATH_TO_FRAGILE = str(Path(__file__).parent.absolute()) + '/Fragile'
sys.exit(subprocess.call(['python3', PATH_TO_FRAGILE]))
